#include <stdio.h>

#include "colors.h"

int main() {

    puts(BLACK_FG "BLACK_FG" RESET_COLOR);
    puts(RED_FG "RED_FG" RESET_COLOR);
    puts(GREEN_FG "GREEN_FG" RESET_COLOR);
    puts(YELLOW_FG "YELLOW_FG" RESET_COLOR);
    puts(BLUE_FG "BLUE_FG" RESET_COLOR);
    puts(MAGENTA_FG "MAGENTA_FG" RESET_COLOR);
    puts(CYAN_FG "CYAN_FG" RESET_COLOR);
    puts(WHITE_FG "WHITE_FG" RESET_COLOR);
    
    puts(BLACK_BRIGHT_FG "BLACK_BRIGHT_FG" RESET_COLOR);
    puts(RED_BRIGHT_FG "RED_BRIGHT_FG" RESET_COLOR);
    puts(GREEN_BRIGHT_FG "GREEN_BRIGHT_FG" RESET_COLOR);
    puts(YELLOW_BRIGHT_FG "YELLOW_BRIGHT_FG" RESET_COLOR);
    puts(BLUE_BRIGHT_FG "BLUE_BRIGHT_FG" RESET_COLOR);
    puts(MAGENTA_BRIGHT_FG "MAGENTA_BRIGHT_FG" RESET_COLOR);
    puts(CYAN_BRIGHT_FG "CYAN_BRIGHT_FG" RESET_COLOR);
    puts(WHITE_BRIGHT_FG "WHITE_BRIGHT_FG" RESET_COLOR);

    puts(BLACK_BG "BLACK_FG" RESET_COLOR);
    puts(RED_BG "RED_FG" RESET_COLOR);
    puts(GREEN_BG "GREEN_FG" RESET_COLOR);
    puts(YELLOW_BG "YELLOW_FG" RESET_COLOR);
    puts(BLUE_BG "BLUE_FG" RESET_COLOR);
    puts(MAGENTA_BG "MAGENTA_FG" RESET_COLOR);
    puts(CYAN_BG "CYAN_FG" RESET_COLOR);
    puts(WHITE_BG "WHITE_FG" RESET_COLOR);
    
    puts(BLACK_BRIGHT_BG "BLACK_BRIGHT_BG" RESET_COLOR);
    puts(RED_BRIGHT_BG "RED_BRIGHT_BG" RESET_COLOR);
    puts(GREEN_BRIGHT_BG "GREEN_BRIGHT_BG" RESET_COLOR);
    puts(YELLOW_BRIGHT_BG "YELLOW_BRIGHT_BG" RESET_COLOR);
    puts(BLUE_BRIGHT_BG "BLUE_BRIGHT_BG" RESET_COLOR);
    puts(MAGENTA_BRIGHT_BG "MAGENTA_BRIGHT_BG" RESET_COLOR);
    puts(CYAN_BRIGHT_BG "CYAN_BRIGHT_BG" RESET_COLOR);
    puts(WHITE_BRIGHT_BG "WHITE_BRIGHT_BG" RESET_COLOR);
    puts("Checks passed");

    return 0;
}

